from tkinter import *
top=Tk()
top.geometry("1400x800")
top.title("WOW")
top.config(bg="black")
welcome=Label(top,text="Welcome Our Page",font=("TimesNewRoman",50,"bold"),bg="black",fg="white")
welcome.place(x=500,y=20)
def login():
    art=Frame(top,bg="blue",height=1500,width=1500)
    art.pack(fill=X)
    student=Label(art,text="Login page",font=("TimesNewRoman",25,"bold"),bg="blue",fg="white")
    student.place(x=700,y=100)
    student=Label(art,text="Username",font=("TimesNewRoman",25,"bold"),bg="blue",fg="white")
    student.place(x=800,y=300)
    student1=Label(art,text="Password",font=("TimesNewRoman",25,"bold"),bg="blue",fg="white")
    student1.place(x=800,y=400)
    box=Entry(top,text="",font=("TimesNewRoman",25,"bold"),fg="black")
    box.place(x=1000,y=300)
    bax=Entry(top,show="*",font=("TimesNewRoman",25,"bold"),fg="black")
    bax.place(x=1000,y=400)
    BUTTON=Button(top,text="LOGIN",font=("TimesNewRoman",25,"bold"),bg="white",fg="black",activebackground="blue",activeforeground="white")
    BUTTON.place(x=800,y=600,height=50,width=100)
    BUTTON=Button(top,text="SIGN IN",font=("TimesNewRoman",25,"bold"),bg="orange",fg="white",activebackground="blue",activeforeground="white")
    BUTTON.place(x=1200,y=700,height=50,width=150)
    student=Label(art,text="Do You Want To Create a Account",font=("TimesNewRoman",25,"bold"),bg="blue",fg="white")
    student.place(x=500,y=700)


BUTTON=Button(top,text="GET STARTED",font=("TimesNewRoman",25,"bold"),bg="white",fg="black",activebackground="green",activeforeground="red",command=login)
BUTTON.place(x=700,y=500)
